### ISSUE TITLE
rpcerror:The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)

### ISSUE THREAD

**Issue by yarinas5** [Raiseku/Telegram-Bot-Local-Database#1]
rpcerror:The api_id/api_hash combination is invalid (caused by ImportBotAuthorizationRequest)
tried 5 different sessions

**Comment by yarinas5** [comment]
![image](https://user-images.githubusercontent.com/23079835/194963450-0ca9a13b-9703-460c-a195-3072eafbb466.png)

**Comment by Raiseku** [comment]
Hello, can you show me your code? i think you are inserting the wrong API_ID and API_HASH given by telegram, or maybe there are some mistakes when you import them via the configparser library
